A6: Chessboard
Tamilarasan-112/cTraining pull request #9
Opened 2024-11-12 09:11 UTC by Tamilarasan-112

2024-12-13 05:29 UTC, ShakthyTMM requested changes

2024-12-16 06:53 UTC, ShakthyTMM requested changes

2024-12-16 06:53 UTC, ShakthyTMM commented on cTraining/cTraining/cTraining.c
> +   }
```suggestion
 for (int index = 0, backTrack = 3; backTrack >= 0; index = index < 4 && backTrack == 3 ? index + 1 : --backTrack) {
      string[2] = uniCode[index];
      Print (string, actualOut);
   }

```

2024-12-16 06:53 UTC, ShakthyTMM commented on cTraining/cTraining/cTraining.c
> +      isEqual ? wprintf (L"Passed\n") : wprintf (L"Failed\n");
It's a cleaner way to write.
```suggestion
      wprintf (isEqual ? L"Passed\n" : L"Failed\n");

```

2024-12-17 05:31 UTC, ShakthyTMM approved these changes

2024-12-19 06:08 UTC, Dakshita-Minocha requested changes

2024-12-19 06:08 UTC, Dakshita-Minocha commented on cTraining/cTraining/ActualOut.txt
> +┃ ♖ ┃ ♘ ┃ ♗ ┃ ♔ ┃ ♕ ┃ ♗ ┃ ♘ ┃ ♖ ┃
Don't push output files

2024-12-19 06:08 UTC, Dakshita-Minocha commented on cTraining/cTraining/cTraining.c
> +      while ((fread (&expChar, sizeof (wchar_t), 1, expOut) && fread (&outChar, sizeof (wchar_t), 1, actOut)) == 1)
Read full file before comparing

2024-12-26 06:37 UTC, Dakshita-Minocha approved these changes

2024-12-26 06:37 UTC, closed without merging